name: Respect Assessment Survey Hosting

on:
  push:
    branches:
      - RESPECTify-prod

jobs:
  build:
    name: Build Assessment Survey Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install app dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Generate Service Worker
        run: npx workbox injectManifest

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.0.3
        with:
          args: deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --only hosting:curiousreader-respect-assessment
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
